ci(private-sync): :construction_worker: abort if no changes

diff --git a/.github/workflows/sync-private.yml b/.github/workflows/sync-private.yml
--- a/.github/workflows/sync-private.yml
+++ b/.github/workflows/sync-private.yml
@@ -30,8 +30,14 @@ jobs:
           git config user.name github-actions[bot]
           git config user.email 41898282+github-actions[bot]@users.noreply.github.com
 
-          git diff | grep -q '\$ANSIBLE_VAULT' && { echo "Aborting: \$ANSIBLE_VAULT found"; exit 1; }
+          git diff | grep -q '\$ANSIBLE_VAULT' && { echo "Aborting: \$ANSIBLE_VAULT found."; exit 1; }
           git add . ':!private-repo'
+
+          if git diff --cached --quiet; then
+            echo "Aborting: no changes to commit."
+            exit 0
+          fi
+
           git commit -m "chore: 🔄 sync changes from private"
           
           branch="private-sync-$(git rev-parse --short HEAD)"
